<a href="https://colab.research.google.com/github/Hansol03/PyTorch-Wikidocs-/blob/main/PyTorch%EB%A1%9C_%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%9E%85%EB%AC%B8_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
[['나는','사과를','좋아해'], ['나는', '바나나를','좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]

[['나는', '사과를', '좋아해'],
 ['나는', '바나나를', '좋아해'],
 ['나는', '사과를', '싫어해'],
 ['나는', '바나나를', '싫어해']]

In [ ]:
'나는' = [0.1, 0.2, 0.9]
'사과를' = [0.3, 0.5, 0.1]
'바나나를' = [0.3, 0.5, 0.2]
'좋아해' = [0.7, 0.6,0.5]
'싫어해' = [0.5, 0.6, 0.7] 

SyntaxError: ignored

In [ ]:
import numpy as np 

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
#파이썬으로 설명하면 Listf를 생성해서 np.array로 1차원 array로 변환함. 
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ',t.ndim)
print('Shape of t:',t.shape)

Rank of t:  1
Shape of t: (7,)


In [ ]:
print('t[0] t[1] t[-1] =', t[0], t[1], t[-1])  #인덱스를 통한 원소 접근 

t[0] t[1] t[-1] = 0.0 1.0 6.0


In [ ]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) #[시작 번호:끝 번호]로 범위 지정을 통해 가져온다. 

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [ ]:
t = np.array([[1., 2., 3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]]) 
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print(t.ndim)
print(t.shape)

2
(4, 3)


In [ ]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim()) # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape 

1
torch.Size([7])
torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1]) #인덱스로 접근 
print(t[2:5], t[4:-1]) #슬라이싱 
print(t[:2], t[3:]) #슬라이싱 

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
t = torch.FloatTensor([[1, 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim()) #rank. 즉, 차원
print(t.size()) #shape

2
torch.Size([4, 3])


In [ ]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다 
print(t[:,1].size()) # 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [ ]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다 

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


#### 브로드캐스팅(Broadcasting)

In [ ]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]]) 
print(m1+m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar 
m1 = torch.FloatTensor([[1, 2]]) 
m2 = torch.FloatTensor([3]) #[3]->[3,3] 
print(m1+m2)

tensor([[4., 5.]])


In [ ]:
# 2x1 Vector +1 X2 Vector 
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]]) 
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
# 텐서의 행렬 곱셈 
m1 = torch.FloatTensor([[1,2], [3,4]]) 
m2 = torch.FloatTensor([[1], [2]]) 
print('Sahpe of Matrix 1: ', m1.shape) # 2x2
print('Shape of Matrix 2: ', m2.shape) # 2x1
print(m1.matmul(m2)) #2x1 

Sahpe of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# element-wise 곱셈 (내적?) 
m1 = torch.FloatTensor([[1,2], [3,4]]) 
m2 = torch.FloatTensor([[1], [2]]) 
print('Shape of Matrix 1: ', m1.shape) #2x2 
print('Shape of Matrix 2: ', m2.shape) #2x1 
print(m1*m2) #2x2
print(m1.mul(m2)) 

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
t = torch.FloatTensor([1,2]) 
print(t.mean()) 

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1,2], [3,4]]) 
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())

tensor(2.5000)


In [ ]:
print(t.mean(dim=0))

tensor([2., 3.])


In [ ]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [ ]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


In [ ]:
t = torch.FloatTensor([[1,2,], [3,4]]) 
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum()) #단순히 원소 전체 덧셈 수행  
print(t.sum(dim=0)) # 행을 제거 
print(t.sum(dim=1)) # 열을 제거 
print(t.sum(dim=-1)) #열을 제거 

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [ ]:
t = torch.FloatTensor([[1,2], [3,4]]) 
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max()) #Reutrns one vlaue: max

tensor(4.)


In [ ]:
print(t.max(dim=0)) # Returns two values: max and argmax 

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [ ]:
print('Max', t.max(dim=0)[0])
print('Argmax:', t.max(dim=0)[1])

Max tensor([3., 4.])
Argmax: tensor([1, 1])


In [ ]:
print(t.max(dim=1)) 
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


#### **3. 텐서 조작하기 (Tensor Manipulation) 2**

4) View - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요! 
 파이토치 텐서의 뷰는 넘파이에서의 Reshape와 같은 역할을 한다. 텐서의 크기(Shape)를 변경해주는 역할. 

In [ ]:
import numpy as np 
import torch

t = np.array([[[0,1,2,],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]]) 
ft =torch.FloatTensor(t)

In [ ]:
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
# 4-1)3차원 텐서에서 2차원 텐서로 변경 
print(ft.view([-1,3])) #ft라는 텐서를 (?,3)의 크기로 변경 
print(ft.view([-1, 3]).shape)

# pytorch의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추함 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [ ]:
print(ft.view([-1,1,3])) 
print(ft.view([-1, 1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [ ]:
# 5) Squeeze - 1인 차원을 제거한다. 

ft = torch.FloatTensor([[0], [1], [2]]) 
print(ft)
print(ft.shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze()) 
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [ ]:
# 6) Unsqueeze - 특정 위치에 1인 차원을 추가한다. 
ft = torch.Tensor([0,1,2]) 
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0)) #인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다. 
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.view(1, -1)) 
print(ft.view(1, -1).shape)
# 2차원으로 바꾸고 싶으면서 첫번째 차원은 1이기를 원한다면 view에서 (1,-1) 을 인자로 사용 

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
print(ft.unsqueeze(1)) 
print(ft.unsqueeze(1).shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.unsqueeze(-1)) 
print(ft.unsqueeze(-1).shape) 

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


**view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절함**

In [ ]:
# 7) 타입 캐스팅(Type Casting) 

lt = torch.LongTensor([1,2,3,4]) 
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
print(lt.float()) 

tensor([1., 2., 3., 4.])


In [ ]:
bt = torch.ByteTensor([True, False, False, True]) 
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
print(bt.long()) 
print(bt.float()) 

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [ ]:
# 8) 연결하기(concatenate) 
x = torch.FloatTensor([[1,2], [3,4]]) 
y = torch.FloatTensor([[5,6], [7,8]]) 

In [ ]:
print(torch.cat([x, y], dim=0)) 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [ ]:
# 9) Stacking 
x = torch.FloatTensor([1,4]) 
y = torch.FloatTensor([2,5]) 
z = torch.FloatTensor([3,6]) 

In [ ]:
print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
# 10) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서 
x = torch.FloatTensor([[0,1,2], [2,1,0]]) 
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하며 값을 1로 채움

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(torch.zeros_like(x)) #입력 텐서와 크기를 동일하게 하며 값을 0으로 채움 

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# 11) In-place Operation (덮어쓰기 연산) 

x =torch.FloatTensor([[1,2], [3,4]]) 

print(x.mul(2.)) # 곱하기 2를 수행한 결과 출력 
print(x) # 기존 결과 출력 

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(x.mul_(2.)) #곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력 
print(x) # 기존의 값 출력 

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### **04. 파이썬 클래스(class)** 

**1. 함수(function)과 클래스(Class)의 차이**

1. 함수로 덧셈기 구현하기 

In [ ]:
result = 0 

In [ ]:
def add(num):
    global result
    result += num 
    return result 

In [ ]:
print(add(3)) 
print(add(4))

3
7


In [ ]:
# 2. 함수(function)로 두 개의 덧셈기 구현 

result1 = 0 
result2 = 0 

def add1(num): 
    global result1
    result1 += num 
    return result1 

def add2(num): 
    global result2 
    result2 += num 
    return result2 

print(add1(3)) 
print(add1(4)) 
print(add2(3)) 
print(add2(7)) 

3
7
3
10


In [ ]:
# 3. class로 덧셈기 구현 

class Calculator: 
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 초기화 함수. 이를 생성자라고 한다. 
        self.result = 0 

    def add(self, num): #객체 생성 후 사용할 수 있는 함수 
        self.result += num 
        return self.result 


In [ ]:
cal1 = Calculator() 
cal2 = Calculator() 

# 클래스는 붕어빵 틀과 같아 클래스 생 성 후 이걸로 여러 객체 만들 수 있음 
# 객체 이름 =클래스이름() 으로 객체 생성 

In [ ]:
print(cal1.add(3)) 
print(cal1.add(4))
print(cal2.add(3)) 
print(cal2.add(7))

3
7
3
10
