<a href="https://colab.research.google.com/github/Hansol03/PyTorch-Wikidocs-/blob/main/Pytorch%EB%A1%9C_%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%9E%85%EB%AC%B8_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**10.순환 신경망(Recurrent Neural Network)**

In [ ]:
# 2. 파이썬으로 RNN 구현하기 
# 아래의 코드는 의사 코드 (pseudocode)로 실제 동작하는 코드가 아님 

hidden_state_t = 0 # 초기 은닉 상태를 0(벡터)로 초기화 
for input_t in input_length: # 각 시점마다 입력을 받는다 
    output_t = tanh(input_t, hidden_state_t) # 각 시점에 대해서 입력과 은닉 상태를 가지고 연산 
    hidden_state_t = output_t # 계산 결과는 현재 시점의 은닉 상태가 된다 

In [ ]:
import numpy as np 

timesteps = 10   #시점의 수. NLP에서는 보통 문장의 길이가 된다. 
input_size = 4   #입력의 차원. NLP에서는 보통 단어 벡터의 차원이 된다. 
hidden_size = 8   #은닉 상태의 크기. 메모리 셀의 용량이다. 

inputs = np.random.random((timesteps, input_size)) #입력에 해당되는 2D 텐서 

hidden_state_t = np.zeros((hidden_size,)) # 초기 은닉 상태는 0(벡터)로 초기화 
# 은닉 상태의 크기 hidden_size로 은닉 상태를 만듬 

In [ ]:
print(hidden_state_t) # 8의 크기를 가지는 은닉 상태. 현재는 초기 은닉 상태로 모든 차원이 0의 값을 가짐. 

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
Wx = np.random.random((hidden_size, input_size)) #(8,4) 크기의 2D 텐서 생성. 입력에 대한 가중치 
Wh = np.random.random((hidden_size, hidden_size)) #(8,8)크기의 2D 텐서 생성. 은닉 상태에 대한 가중치 
b = np.random.random((hidden_size,)) # (8,) 크기의 1D 텐서 생성. 이 값은 편향(bias) 

In [ ]:
print(np.shape(Wx)) 
print(np.shape(Wh)) 
print(np.shape(b)) 

(8, 4)
(8, 8)
(8,)


In [ ]:
total_hidden_states = [] 

# 메모리 셀 동작 
for input_t in inputs: # 각 시점에 따라서 입력값이 입력됨 
    output_t = np.tanh(np.dot(Wx, input_t) + np.dot(Wh, hidden_state_t) + b) # Wx * Xt + Wh * Ht-1 + b(bias) 
    total_hidden_states.append(list(output_t)) # 각 시점의 은닉 상태의 값을 계속해서 축적 
    print(np.shape(total_hidden_states)) # 각 시점 t별 메모리 셀의 출력의 크기는 (timestep, output_dim) 
    hidden_state_t = output_t 

total_hidden_states = np.stack(total_hidden_states, axis = 0) 
# 출력 시 값을 깔끔하게 해준다. 

print(total_hidden_states) # (timesteps, output_dim)의 크기. 이 경우 (10, 8)의 크기를 가지는 메모리 셀의 2D 텐서를 출력 

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
[[0.95901259 0.95487794 0.86839032 0.88284809 0.98961044 0.97589947
  0.94790078 0.96294715]
 [0.99992464 0.99993898 0.99795967 0.9981817  0.99999487 0.9999366
  0.9991409  0.99990779]
 [0.99998601 0.99999137 0.99918635 0.99958979 0.99999922 0.99999247
  0.99974652 0.99997534]
 [0.99998908 0.99999208 0.99957852 0.99953286 0.99999951 0.99999296
  0.99982151 0.99998536]
 [0.9999618  0.99998162 0.99890976 0.99857148 0.99999828 0.99997415
  0.99970139 0.99996166]
 [0.99997285 0.99998298 0.99846931 0.99943038 0.99999831 0.99998419
  0.99948338 0.99994924]
 [0.99998353 0.99999319 0.99957853 0.99896946 0.99999947 0.99998978
  0.99990594 0.99998522]
 [0.99995807 0.99997468 0.99854815 0.99904754 0.99999797 0.99996991
  0.99943461 0.99993543]
 [0.99999191 0.99999314 0.99959458 0.99973905 0.99999962 0.99999495
  0.99979133 0.99998414]
 [0.99998079 0.99998053 0.99973159 0.99929071 0.99999954 0.99997727
  0.99970162 0.99997387]]

In [ ]:
# 3. 파이토치의 nn.RNN()
import torch
import torch.nn as nn 

In [ ]:
input_size = 5 #입력의 크기 
hidden_size = 8 #은닉 상태의 크기 

In [ ]:
# (batch_size, time_steps, input_size) 
inputs = torch.Tensor(1, 10, 5) 

In [ ]:
cell = nn.RNN(input_size, hidden_size, batch_first=True) 

In [ ]:
outputs, _status = cell(inputs)

In [ ]:
print(outputs.shape) # 모든 time-steps의 hidden_state

torch.Size([1, 10, 8])


In [ ]:
print(_status.shape) # 최종 itme-step의 hidden_state

torch.Size([1, 1, 8])


In [ ]:
# (batch_size, time_steps, imput_size) 
inputs = torch.Tensor(1, 10, 5) 

In [ ]:
cell = nn.RNN(input_size = 5, hidden_size = 8, num_layers =2, batch_first = True)

In [ ]:
outputs, _status = cell(inputs) 

In [ ]:
print(outputs.shape) # 모든 time-step의 hidden_state 

torch.Size([1, 10, 8])


In [ ]:
print(_status.shape) #(층의 개수, 배치 크기, 은닉 상태의 크기)

torch.Size([2, 1, 8])


In [ ]:
# (batch_sizem time_step, input_size) 
inputs = torch.Tensor(1, 10, 5) 

In [ ]:
cell = nn.RNN(input_size = 5, hidden_size = 8, num_layers =2, batch_first=True, bidirectional = True)

In [ ]:
outputs, _status = cell(inputs) 

In [ ]:
print(outputs.shape) #(배치크기, 시퀀스 길이, 은닉 상태의 크기 x2)

torch.Size([1, 10, 16])


In [ ]:
print(_status.shape) #(층의 개수 x2, 배치 크기, 은닉 상태의 크기)

torch.Size([4, 1, 8])


In [ ]:
# 4. 파이토치의 nn.LSTM()
nn.RNN(input_dim, hidden_size, batch_first=True) 

NameError: ignored

In [ ]:
nn.LSTM(input_dim, hidden_size, batch_first = True) 

###**11.다대다 RNN을 이용한 텍스트 생성**

In [ ]:
# 1.문자 단위 RNN(Char RNN) 
import torch
import torch.nn as nn 
import torch.optim as optim
import numpy as np 

In [ ]:
# 1. 훈련 데이터 전처리하기 
input_str ='apple'
label_str = 'pple!'
char_vocab = sorted(list(set(input_str+label_str))) 
vocab_size = len(char_vocab) 
print('문자 집합의 크기 : {}'.format(vocab_size))

문자 집합의 크기 : 5


In [ ]:
input_size = vocab_size # 입력의 크기는 문자 집합의 크기 
hidden_size = 5 
output_size = 5
learning_rate = 0.1

In [ ]:
char_to_index = dict((c, i) for i, c in enumerate(char_vocab)) #문자에 고유한 정수 인덱스 부여 
print(char_to_index)

{'!': 0, 'a': 1, 'e': 2, 'l': 3, 'p': 4}


In [ ]:
index_to_char = {} 
for key, value in char_to_index.items():
    index_to_char[value] = key
print(index_to_char)

{0: '!', 1: 'a', 2: 'e', 3: 'l', 4: 'p'}


In [ ]:
x_data = [char_to_index[c] for c in input_str] 
y_data = [char_to_index[c] for c in label_str] 
print(x_data)
print(y_data)

[1, 4, 4, 3, 2]
[4, 4, 3, 2, 0]


In [ ]:
# 배치 차원 추가 
# 텐서 연산인 unsqueeze(0) 를 통해 해결할 수도 있었음. 
x_data = [x_data] 
y_data = [y_data] 
print(x_data) 
print(y_data)

[[1, 4, 4, 3, 2]]
[[4, 4, 3, 2, 0]]


In [ ]:
x_one_hot = [np.eye(vocab_size)[x] for x in x_data]
print(x_one_hot)

[array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])]


In [ ]:
X = torch.FloatTensor(x_one_hot) 
Y = torch.LongTensor(y_data) 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  """Entry point for launching an IPython kernel.


In [ ]:
print('훈련 데이터의 크기: {}'.format(X.shape)) 
print('레이블의 크기: {}'.format(Y.shape)) 

훈련 데이터의 크기: torch.Size([1, 5, 5])
레이블의 크기: torch.Size([1, 5])


In [ ]:
# 2. 모델 구현하기 
class Net(torch.nn.Module): 
    def __init__(self, input_size, hidden_size, output_size): 
        super(Net, self).__init__() 
        self.rnn = torch.nn.RNN(input_size, hidden_size, batch_first=True) #RNN 셀 구현 
        self.fc = torch.nn.Linear(hidden_size, output_size, bias=True) # 출력층 구현 

    def forward(self, x): #구현한 RNN 셀과 출력층을 연결 
        x, _status = self.rnn(x) 
        x = self.fc(x) 
        return x 

In [ ]:
net = Net(input_size, hidden_size, output_size) 

In [ ]:
outputs = net(X) 
print(outputs.shape) #3차원 텐서 

torch.Size([1, 5, 5])


In [ ]:
print(outputs.view(-1, input_size).shape) # 2차원 텐서로 변환 

torch.Size([5, 5])


In [ ]:
print(Y.shape)
print(Y.view(-1).shape)

torch.Size([1, 5])
torch.Size([5])


In [ ]:
criterion = torch.nn.CrossEntropyLoss() 
optimizer = optim.Adam(net.parameters(), learning_rate) 

In [ ]:
for i in range(100): 
    optimizer.zero_grad()
    outputs = net(X) 
    loss = criterion(outputs.view(-1, input_size), Y.view(-1)) # view를 하는 이유는 Batch 차원 제거를 위해 
    loss.backward() # 기울기 계산 
    optimizer.step() #아까 optimizer 선언 시 넣어둔 파라미터 업데이트 

    # 아래 세 줄은 모델이 실제 어떻게 예측했는지를 확인하기 위한 코드 
    result = outputs.data.numpy().argmax(axis=2) #최종 예측값인 각 time-step 별 5차원 벡터에 대해서 가장 높은 값의 인덱스를 선택 
    result_str = ''.join([index_to_char[c] for c in np.squeeze(result)]) 
    print(i, 'loss:', loss.item(), 'prediction: ', result, 'true Y: ', y_data, 'prediction str: ', result_str)

0 loss: 1.629637360572815 prediction:  [[4 0 2 4 4]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  p!epp
1 loss: 1.354446291923523 prediction:  [[4 4 2 2 2]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  ppeee
2 loss: 1.1438581943511963 prediction:  [[4 4 3 3 4]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  ppllp
3 loss: 0.9643559455871582 prediction:  [[4 4 3 3 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  ppll!
4 loss: 0.77979576587677 prediction:  [[4 4 3 3 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  ppll!
5 loss: 0.6285192370414734 prediction:  [[4 4 3 2 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pple!
6 loss: 0.5028437376022339 prediction:  [[4 4 3 2 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pple!
7 loss: 0.39548078179359436 prediction:  [[4 4 3 2 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pple!
8 loss: 0.3268114924430847 prediction:  [[4 4 3 2 0]] true Y:  [[4, 4, 3, 2, 0]] prediction str:  pple!
9 loss: 0.2600756883621216 prediction:  [[4 4 3 2 0]] true Y:  [[4,

###**02. 문자 단위 RNN(Char RNN) - 더 많은 데이터**

In [ ]:
# 2. 문자 단위 RNN(Char RNN) 

import torch 
import torch.nn as nn 
import torch.optim as optim 

In [ ]:
# 1. 훈련 데이터 전처리하기 

sentence = ("if you want to build a ship, don't drum up people together to" 
            "collect wood and don't assign them tasks and work, but rather "
            "teach them to long for the endless immensity of the sea.") 

In [ ]:
char_set = list(set(sentence)) #중복을 제거한 문자 집합 생성 
char_dic = {c: i for i, c in enumerate(char_set)} # 각 문자에 정수 인코딩 

print(char_dic) # 공백도 여기서는 하나의 원소 

{'d': 0, ',': 1, 'b': 2, 'm': 3, 'i': 4, 'h': 5, 'g': 6, 'o': 7, 'l': 8, 'k': 9, 'f': 10, 'r': 11, 'y': 12, 'n': 13, 'c': 14, 'u': 15, "'": 16, 'p': 17, 'w': 18, ' ': 19, 's': 20, 'e': 21, 't': 22, '.': 23, 'a': 24}


In [ ]:
dic_size = len(char_dic) 
print('문자 집합의 크기: {}'.format(dic_size))

문자 집합의 크기: 25


In [ ]:
# 하이퍼파라미터 설정 
hidden_size = dic_size
sequence_length = 10 # 임의 숫자 지정 
learning_rate = 0.1 

In [ ]:
# 데이터 구성 
x_data = [] 
y_data = [] 

for i in range (0, len(sentence) - sequence_length): 
    x_str = sentence[i:i + sequence_length] 
    y_str = sentence[i +1: i+ sequence_length + 1]
    print(i, x_str, '->', y_str) 

    x_data.append([char_dic[c] for c in x_str]) # x str to index 
    y_data.append([char_dic[c] for c in y_str]) # y str to index 

0 if you wan -> f you want
1 f you want ->  you want 
2  you want  -> you want t
3 you want t -> ou want to
4 ou want to -> u want to 
5 u want to  ->  want to b
6  want to b -> want to bu
7 want to bu -> ant to bui
8 ant to bui -> nt to buil
9 nt to buil -> t to build
10 t to build ->  to build 
11  to build  -> to build a
12 to build a -> o build a 
13 o build a  ->  build a s
14  build a s -> build a sh
15 build a sh -> uild a shi
16 uild a shi -> ild a ship
17 ild a ship -> ld a ship,
18 ld a ship, -> d a ship, 
19 d a ship,  ->  a ship, d
20  a ship, d -> a ship, do
21 a ship, do ->  ship, don
22  ship, don -> ship, don'
23 ship, don' -> hip, don't
24 hip, don't -> ip, don't 
25 ip, don't  -> p, don't d
26 p, don't d -> , don't dr
27 , don't dr ->  don't dru
28  don't dru -> don't drum
29 don't drum -> on't drum 
30 on't drum  -> n't drum u
31 n't drum u -> 't drum up
32 't drum up -> t drum up 
33 t drum up  ->  drum up p
34  drum up p -> drum up pe
35 drum up pe -> rum up peo
36

In [ ]:
print(x_data[0])
print(y_data[0])

[4, 10, 19, 12, 7, 15, 19, 18, 24, 13]
[10, 19, 12, 7, 15, 19, 18, 24, 13, 22]


In [ ]:
import numpy as np

x_one_hot = [np.eye(dic_size)[x] for x in x_data] # x 데이터는 원-핫 인코딩 
X = torch.FloatTensor(x_one_hot) 
Y = torch.LongTensor(y_data)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  after removing the cwd from sys.path.


In [ ]:
print('훈련 데이터의 크기: {}'.format(X.shape))
print('레이블의 크기: {}'.format(Y.shape)) 

훈련 데이터의 크기: torch.Size([169, 10, 25])
레이블의 크기: torch.Size([169, 10])


In [ ]:
print(X[0])

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [ ]:
# 2. 모델 구현하기 

class Net(torch.nn.Module): 
    def __init__(self, input_dim, hidden_dim, layers): # 현재 hidden_size는 dic)size와 같음 
        super(Net, self).__init__() 
        self.rnn = torch.nn.RNN(input_dim, hidden_dim, num_layers=layers, batch_first=True) 
        self.fc = torch.nn.Linear(hidden_dim, hidden_dim, bias=True) 

    def forward(self, x): 
        x, _status = self.rnn(x) 
        x = self.fc(x) 
        return x 

In [ ]:
net = Net(dic_size, hidden_size, 2) # 이번에는 층을 두개 쌓습니다. 

In [ ]:
criterion = torch.nn.CrossEntropyLoss() 
optimizer = optim.Adam(net.parameters(), learning_rate) 

In [ ]:
outputs = net(X) 
print(outputs.shape) # 3차원 텐서 

torch.Size([169, 10, 25])


In [ ]:
print(outputs.view(-1, dic_size).shape) # 2차원 텐서로 변환. 

torch.Size([1690, 25])


In [ ]:
print(Y.shape) 
print(Y.view(-1).shape)

torch.Size([169, 10])
torch.Size([1690])


In [ ]:
for i in range(100): 
    optimizer.zero_grad() 
    outputs = net(X) #(170, 10, 25) 크기를 가진 텐서를 매 에포크마다 모델의 입력으로 사용 
    loss = criterion(outputs.view(-1, dic_size), Y.view(-1)) 
    loss.backward() 
    optimizer.step() 

    # results의 텐서 크기는 (170, 10) 
    results = outputs.argmax(dim=2) 
    predict_str = "" 
    for j, result in enumerate(results): 
        if j == 0: #처음에는 예측 결과를 전부 가져오지만 
            predict_str += ''.join([char_set[t] for t in result]) 
        else: # 그 다음에는 마지막 글자만 반복 추가 
            predict_str += char_set[result[-1]] 

    print(predict_str) 

ddddddddddddddddddddddddddddddddtddodddddddd ddddddddddddddddddddddddddddddddddddtdddddddddddddddddddddddddddddddddddddddddddddddddddddddeddedddddddddddtdddddddddddddddddtddddddd
   o   o o  o   o o       o o   o    to o  o          o o            o o   o                    o  o     o     to     o          o       o    o  to   o   o o o      o o  to   o  
 lstdrdtdrdthtmdtddtddpd mdr. h . drdrdto rdr  rduh . td.trdto tdro ut rdtdt.dtut. drdrdt.stdhdrdtrdrdt. m htm ddrd rdmdrdto mdrdtdd rdt.dtd td .sdtrdrdro rdrdtrdtrrt  rdrdth rdt
 t    st t thr.r tk tt  t   trtttt .rt thrkt tt ithr t t  tr tt ttrtr    .tr t  dt  drtt  tr t tt  rrtt r tr t t r t t rt t rtr ttrrrtr tt ttf r t  .rt  trr ttt t tt  tr t  tr r 
 tto  to ttto stet  tt ttttt ttttttt t tt tt t tttott  tt ttt  tt tttt  tttttt t t t  t t  t t ttt  tt ettt  t t   ttt tt tte t tott  tttttt ttt te tttt ttt  t  t      t t tttttt
  to  woe  eo ben t e ohe   to  t b  e bh toh lh  o  tle  oe      t  o l  o  tonltetbo t  lhen to l  ito 

###**03. 단어 단위 RNN - 임베딩사용**

In [ ]:
# 1. 훈련 데이터 전처리하기 

import torch 
import torch.nn as nn 
import torch.optim as optim 

In [ ]:
sentence = 'Repeat is the best medicine for memory'.split() 

In [ ]:
vocab = list(set(sentence)) 
print(vocab)

['the', 'Repeat', 'memory', 'medicine', 'for', 'best', 'is']


In [ ]:
word2index = {tkn: i for i, tkn in enumerate(vocab, 1)} # 단어에 고유한 정수 부여 
word2index['<unk>']=0 

In [ ]:
print(word2index)

{'the': 1, 'Repeat': 2, 'memory': 3, 'medicine': 4, 'for': 5, 'best': 6, 'is': 7, '<unk>': 0}


In [ ]:
print(word2index['memory'])

3


In [ ]:
# 수치화된 데이터를 단어로 바꾸기 위한 사전 
index2word = {v: k for k, v in word2index.items()} 
print(index2word)

{1: 'the', 2: 'Repeat', 3: 'memory', 4: 'medicine', 5: 'for', 6: 'best', 7: 'is', 0: '<unk>'}


In [ ]:
print(index2word[2])

Repeat


In [ ]:
def build_data(sentence, word2index): 
    encoded = [word2index[token] for token in sentence] # 각 문자를 정수로 변환 
    input_seq, label_seq = encoded[:-1], encoded[1:] # 입력 시퀀스와 레이블 시퀀스를 분리 
    input_seq = torch.LongTensor(input_seq).unsqueeze(0) # 배치 차원 추가 
    label_seq = torch.LongTensor(label_seq).unsqueeze(0) # 배치 차원 추가 
    return input_seq, label_seq

In [ ]:
X, Y = build_data(sentence, word2index)

In [ ]:
print(X) 
print(Y)

tensor([[2, 7, 1, 6, 4, 5]])
tensor([[7, 1, 6, 4, 5, 3]])


In [ ]:
# 2. 모델 구현하기 
class Net(nn.Module): 
    def __init__(self, vocab_size, input_size, hidden_size, batch_first=True): 
        super(Net, self).__init__()
        self.embedding_layer = nn.Embedding(num_embeddings=vocab_size, #워드 임베딩 
                                            embedding_dim=input_size)
        self.rnn_layer = nn.RNN(input_size, hidden_size, # 입력 차원, 은닉상태의 크기 정의 
                                batch_first=batch_first) 
        self.linear = nn.Linear(hidden_size, vocab_size) # 출력은 원-핫 벡터의 크기를 가져야함. 또는 단어 집합의 크기만큼 가져야함. 

    def forward(self, x): 
        # 1. 임베딩 층
        # 크기변화: (배치 크기, 시퀀스 길이) => (배치 크기, 시퀀스 길이, 임베딩 차원) 
        output = self.embedding_layer(x) 
        # 2. RNN 층
        # 크기변화: (배치 크기, 시퀀스 길이, 임베딩 차원)
        # => output (배치 크기, 시퀀스 길이, 은닉층 크기) , hidden(1, 배치 크기, 은닉층 크기) 
        output, hidden = self.rnn_layer(output) 
        # 3. 최종 출력층
        # 크기변화: (배치 크기, 시퀀스 길이, 은닉층 크기) => (배치 크기, 시퀀스 길이, 단어장 크기) 
        output = self.linear(output) 
        # 4. view를 통해서 배치 차원 제거 
        # 크기변화: (배치 크기, 시퀀스 길이, 단어장 크기) => (배치 크기*시퀀스 길이, 단어장 크기)
        return output.view(-1, output.size(2))

In [ ]:
# hyperparameters 
vocab_size = len(word2index) # 단어장 크기는 임베딩층, 최종 출력층에 사용된다. <unk>토큰을 크기에 포함한다.
input_size = 5 #임베딩된 차원의 크기및 RNN층 입력 차원의 크기
hidden_size = 20 # RNN의 은닉층 크기

In [ ]:
# 모델 생성 
model = Net(vocab_size, input_size, hidden_size, batch_first=True) 
# 손실 함수 정의
loss_function = nn.CrossEntropyLoss() # 소프트맥스 함수 포함이며 실제값은 원-핫 인코딩 안 해도됨
# optimizer 정의의
optimizer = optim.Adam(params=model.parameters()) 

In [ ]:
#임의로 예측 해보기. 가중치는 전부 랜덤 초기화된 상태이다. 
output = model(X) 
print(output) 

tensor([[ 0.2703,  0.0212, -0.1778, -0.1823, -0.3124, -0.0098,  0.0105,  0.1018],
        [ 0.1278,  0.1028, -0.1142, -0.1996, -0.2963, -0.0347, -0.0227, -0.0950],
        [ 0.0596, -0.1483, -0.0788,  0.3530, -0.0436, -0.1035,  0.0769,  0.0761],
        [-0.2229, -0.0556, -0.1420, -0.9191, -0.4391, -0.2798, -0.1591, -0.1070],
        [ 0.0684, -0.1317, -0.1057, -0.6691, -0.5215,  0.0618,  0.0842,  0.1171],
        [ 0.1225,  0.0263,  0.0281, -0.4478, -0.4442, -0.1227,  0.0495,  0.0472]],
       grad_fn=<ViewBackward0>)


In [ ]:
print(output.shape)

torch.Size([6, 8])


In [ ]:
# 수치화된 데이터를 단어로 전환하는 함수
decode = lambda y: [index2word.get(x) for x in y]

In [ ]:
# 훈련 시작
for step in range(201): 
    # 경사 초기화
    optimizer.zero_grad() 
    # 순방향 전파
    output = model(X) 
    # 손실값 계산
    loss = loss_function(output, Y.view(-1)) 
    # 역방향 전파
    loss.backward() 
    # 매개변수 업데이트 
    optimizer.step() 
    # 기록
    if step % 40 == 0: 
        print('[{:02d}/201] {:.4f} '.format(step+1, loss)) 
        pred = output.softmax(-1).argmax(-1).tolist() 
        print(' '.join(['Repeat'] + decode(pred))) 
        print()

[01/201] 0.1414 
Repeat is the best medicine for memory

[41/201] 0.0911 
Repeat is the best medicine for memory

[81/201] 0.0642 
Repeat is the best medicine for memory

[121/201] 0.0482 
Repeat is the best medicine for memory

[161/201] 0.0378 
Repeat is the best medicine for memory

[201/201] 0.0306 
Repeat is the best medicine for memory

