<a href="https://colab.research.google.com/github/Hansol03/PyTorch-Wikidocs-/blob/main/PyTorch%EB%A1%9C_%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%9E%85%EB%AC%B8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **03. 선형 회귀(Linear Regression)**

In [ ]:
# 1. 기본 셋팅
import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.optim as optim 

In [ ]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다. 
torch.manual_seed(1) 

In [ ]:
# 2. 변수 선언 
x_train = torch.FloatTensor([[1], [2], [3]]) 
y_train = torch.FloatTensor([[2], [4], [6]]) 

In [ ]:
print(x_train) 
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [ ]:
print(y_train) 
print(y_train.shape) 

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [ ]:
# 3. 가중치와 편향의 초기화 
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시
W = torch.zeros(1, requires_grad=True) 
# 가중치 W 출력 
print(W)

# requires_grad=True는 변수가 학습을 통해 계속 값이 변경되는 변수임을 의미 
# 텐서에는 requires_grad 를 True로 설정하면 자동 미분 기능이 적용됨. 
# 이게 적용된 텐서에 연산을 하면 계산 그래프가 생성되며 backward 함수 호출하면 그래프로부터 자동으로 미분 계산 

tensor([0.], requires_grad=True)


In [ ]:
b = torch.zeros(1, requires_grad=True) 
print(b)

tensor([0.], requires_grad=True)


In [ ]:
# 4. 가설 세우기 
hypothesis = x_train * W + b 
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [ ]:
# 5. cost function 선언하기 
# 선형회귀 비용함수인 평균제곱오차 선언 
# 앞서 배운 torch.mean으로 평균을 구한다 
cost = torch.mean((hypothesis - y_train)**2) 
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [ ]:
# 6. 경사 하강법 구현하기 
optimizer = optim.SGD([W, b], lr=0.01)

In [ ]:
# gradient를 0으로 초기화 
optimizer.zero_grad() 
# 비용함수를 미분하여 gradient 계산 
cost.backward() 
# W와 b를 업데이트 
optimizer.step() 

In [ ]:
# 7. 전체 코드 

# 데이터 
x_train = torch.FloatTensor([[1], [2], [3]]) 
y_train = torch.FloatTensor([[2], [4], [6]]) 
# 모델 초기화 
W = torch.zeros(1, requires_grad=True) 
b = torch.zeros(1, requires_grad=True) 
# optimizer 설정 
optimizer = optim.SGD([W, b], lr=0.01) 

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복 
for epoch in range(nb_epochs +1): 

    # H(x) 계산
    hypothesis = x_train * W + b 

    # cost 계산 
    cost = torch.mean((hypothesis - y_train) **2) 

    # cost로 H(x) 개선 
    optimizer.zero_grad() 
    cost.backward() 
    optimizer.step() 

    # 100번마다 로그 출력 
    if epoch % 100 ==0: 
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

In [ ]:
# 5. optimizer.zero_grad()가 필요한 이유 
# 파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있기 때문에 

import torch
w =torch.tensor(2.0, requires_grad=True) 

nb_epochs = 20 
for epoch in range(nb_epochs + 1): 

    z = 2*w 

    z.backward() 
    print('수식을 w로 미분한 값: {}'.format(w.grad)) 

수식을 w로 미분한 값: 2.0
수식을 w로 미분한 값: 4.0
수식을 w로 미분한 값: 6.0
수식을 w로 미분한 값: 8.0
수식을 w로 미분한 값: 10.0
수식을 w로 미분한 값: 12.0
수식을 w로 미분한 값: 14.0
수식을 w로 미분한 값: 16.0
수식을 w로 미분한 값: 18.0
수식을 w로 미분한 값: 20.0
수식을 w로 미분한 값: 22.0
수식을 w로 미분한 값: 24.0
수식을 w로 미분한 값: 26.0
수식을 w로 미분한 값: 28.0
수식을 w로 미분한 값: 30.0
수식을 w로 미분한 값: 32.0
수식을 w로 미분한 값: 34.0
수식을 w로 미분한 값: 36.0
수식을 w로 미분한 값: 38.0
수식을 w로 미분한 값: 40.0
수식을 w로 미분한 값: 42.0


#### **02. 자동미분**

In [ ]:
import torch 

In [ ]:
# 값이 2인 임의의 스칼라 텐서 w 선언 
w = torch.tensor(2.0, requires_grad=True) 

In [ ]:
y = w**2 
z = 2*y + 5 

In [ ]:
# w에 대해 미분. .backward()를 호출하면 해당 수식의 w에 대한 기울기 계산 
z.backward() 

In [ ]:
print('수식을 w로 미분한 값: {}'.format(w.grad)) 

수식을 w로 미분한 값: 8.0


#### **03.다중 선형 회귀 (Multivariable Linear regression)**

In [ ]:
import torch 
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim 

In [ ]:
torch.manual_seed(1) 

In [ ]:
# 훈련 데이터 
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]]) 
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]]) 
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]]) 
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])  

In [ ]:
# 가중치 w와 편향 b 초기화 
w1 = torch.zeros(1, requires_grad=True) 
w2 = torch.zeros(1, requires_grad=True) 
w3 = torch.zeros(1, requires_grad=True) 
b = torch.zeros(1, requires_grad=True)

In [ ]:
# optimizer 설정 
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5) 

nb_epochs = 1000
for epoch in range(nb_epochs + 1): 

    # H(x) 계산 
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b 

    # cost 계산 
    cost = torch.mean((hypothesis - y_train)**2) 

    # cost로 H(x) 개선 
    optimizer.zero_grad() 
    cost.backward() 
    optimizer.step() 

    # 100번마다 로그 출력 
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item() 

        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


In [ ]:
# 4. 행렬 연산을 고려하여 파이토치로 구현하기 
x_train = torch.FloatTensor([[73, 80, 75], 
                             [93, 88, 93], 
                             [89, 91, 80], 
                             [96, 98, 100], 
                             [73, 66, 70]]) 
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) 

In [ ]:
print(x_train.shape) 
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [ ]:
# 가중치와 편향 선언 
W = torch.zeros((3,1), requires_grad=True) 
b = torch.zeros(1, requires_grad=True) 

In [ ]:
hypothesis = x_train.matmul(W) + b

In [ ]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80], 
                             [96, 98, 100], 
                             [73, 66, 70]]) 
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) 

#모델 초기화 
W = torch.zeros((3,1), requires_grad=True) 
b = torch.zeros(1, requires_grad=True) 
# optimizer 설정 
optimizer = optim.SGD([W, b], lr=1e-5) 

nb_epochs = 20
for epoch in range(nb_epochs + 1): 

    # H(x) 계산 
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다. 
    hypothesis = x_train.matmul(W) + b 

    # cost 계산 
    cost = torch.mean((hypothesis - y_train)**2) 

    # cost로 H(x) 개선 
    optimizer.zero_grad() 
    cost.backward() 
    optimizer.step() 

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

####**04. nn.Module로 구현하는 선형회귀**

In [ ]:
import torch
import torch.nn as nn 
import torch.nn.functional as F 


In [ ]:
torch.manual_seed(1) 

In [ ]:
# 데이터 
x_train = torch.FloatTensor([[1], [2], [3]]) 
y_train = torch.FloatTensor([[2], [4] ,[6]]) 

In [ ]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 Input_dim=1, output_dim =1. 
model =nn.Linear(1,1) 

In [ ]:
print(list(model.parameters())) 

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [ ]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01 
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)  

In [ ]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복 
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산 
    prediction = model(x_train) 

    # cost 계산 
    cost = F.mse_loss(prediction, y_train)  # <== 파이토치에서 제공하는 평균 제곱 오차 함수 

    # cost로 H(x) 개선하는 부분 
    # gradient를 0으로 초기화 
    optimizer.zero_grad() 
    # 비용 함수를 미분하여 gradient 계산 
    cost.backward()  #backward 계산 
    # W와 b를 업데이트 
    optimizer.step() 

    if epoch % 100 == 0:
    # 100번마다 로그 출력 
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        )) 


Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
# 임의의 입력 4를 선언 
new_var = torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장 
pred_y = model(new_var) # forward 연산 
# y = 2x 이므로 입력이 4라면 Y가 8에 가까운 값이 나와야 제대로 학습이 된것 
print('훈련 후 입력이 4일때의 예측 값: ', pred_y)

훈련 후 입력이 4일때의 예측 값:  tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [ ]:
# 2. 다중 선형 회귀 구현하기 
import torch 
import torch.nn as nn 
import torch.nn.functional as F 

In [ ]:
torch.manual_seed(1) 

In [ ]:
# 데이터 
x_train = torch.FloatTensor([[73, 80, 75], 
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]]) 
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) 

In [ ]:
# 모델을 선언 및 초기회. 다중 선형 회귀이므로 input_dim=3, output_dim=1. 
model = nn.Linear(3,1) 

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1): 

    # H(x) 계산 
    prediction = model(x_train) 
    # model(x_train)은 model.forward(x_train) 와 동일함 

    # cost 계산 
    cost = F.mse_loss(prediction, y_train)  # <== 파이토치에서 제공하는 평균 제곱 오차 함수 

    # cost로 H(x) 개선하는 부분
    # gradient 0으로 초기화 
    optimizer.zero_grad() 
    # 비용함수를 미분하여 gradient 계산
    cost.backward() 
    # W와 b를 업데이트
    optimizer.step() 

    if epoch % 100 == 0:
        # 100번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [ ]:
# 임의의 입력 [73, 80, 75] 를 선언
new_var = torch.FloatTensor([[73, 80, 75]]) 
# 입력한한 값 [73, 80, 75]에 대해서 예측값 y를 리턴 받아서 pred_y에 저장
pred_y = model(new_var) 
print('훈련 후 입력이 73, 80, 75일때의 예측값: ', pred_y) 

훈련 후 입력이 73, 80, 75일때의 예측값:  tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters())) 

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


####**05.클래스로 파이토치 모델 구현하기**

In [ ]:
# 1. 모델을 클래스로 구현하기 
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output+dim1. 
model = nn.Linear(1,1)

In [ ]:
class LinearRegressionModel(nn.Module): #torch.nn.Module을 상속받는 파이썬 클래스 
    def __init__(self): 
        super().__init__() 
        self.linear = nn.Linear(1,1)  #단순 선형 회귀이므로 input_dim = 1, output_dim=1 

    def forward(self, x): 
        return self.linear(x) 

In [ ]:
model = LinearRegressionModel()

In [ ]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim =3, output_dim=1
model = nn.Linear(3,1) 

In [ ]:
class MultivariateLinearRegressionModel(nn.Module): 
    def __init__(self):
        super().__init__() 
        self.linear = nn.Linear(3,1)  #다중 선형 회귀이므로 input_dim=3, output_dim=1 

    def forward(self, x): 
        return self.linear(x)

In [ ]:
model = MultivariateLinearRegressionModel()

In [ ]:
# 2. 단순 선형 회귀 클래스로 구현하기 
import torch 
import torch.nn as nn 
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1) 

In [ ]:
# 데이터 
x_train = torch.FloatTensor([[1], [2], [3]]) 
y_train = torch.FloatTensor([[2], [4], [6]]) 

In [ ]:
class LinearRegressionModel(nn.Module): 
    def __init__(self): 
        super().__init__() 
        self.linear = nn.Linear(1,1) 

    def forward(self, x): 
        return self.linear(x) 

In [ ]:
model = LinearRegressionModel()

In [ ]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01 
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [ ]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복 
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산 
    prediction = model(x_train) 

    # cost 계산 
    cost = F.mse_loss(prediction, y_train)  # <== 파이토치에서 제공하는 평균 제곱 오차 함수 

    # cost로 H(x) 개선하는 부분 
    # gradient를 0으로 초기화 
    optimizer.zero_grad() 
    # 비용 함수를 미분하여 gradient 계산 
    cost.backward()  # backward 연산 
    # W와 b를 업데이트 
    optimizer.step() 

    if epoch % 100 == 0: 
    # 100번마다 로그 출력 
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [ ]:
# 3. 다중 선형 회귀 클래스로 구현하기 
import torch 
import torch.nn as nn 
import torch.nn.functional as F 

In [ ]:
torch.manual_seed(1) 

In [ ]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93], 
                             [89, 91, 90], 
                             [96, 98, 100],
                             [73, 66, 70]]) 
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) 

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__() 
        self.linear = nn.Linear(3,1)  #다중 선형 회귀이므로 input_dim = 3, output_dim =1

    def forward(self, x):
        return self.linear(x)

In [ ]:
model = MultivariateLinearRegressionModel()

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1): 

    # H(x) 계산 
    prediction = model(x_train) 
    # model(x_train)은 model.forward(x_train)와 동일함 

    # cost 계산 
    cost = F.mse_loss(prediction, y_train)  # <== 파이토치에서 제공하는 평균 제곱 오차 함수 

    # cost로 H(x) 개선하는 부분 
    # gradient를 0으로 초기화 
    optimizer.zero_grad() 
    # 비용 함수를 미분하여 gradient 계산 
    cost.backward() 
    # W와 b를 업데이트 
    optimizer.step() 

    if epoch % 100 == 0:
    # 100번마다 로그 출력 
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/2000 Cost: 9926.265625
Epoch  100/2000 Cost: 0.225971
Epoch  200/2000 Cost: 0.223895
Epoch  300/2000 Cost: 0.221921
Epoch  400/2000 Cost: 0.220036
Epoch  500/2000 Cost: 0.218253
Epoch  600/2000 Cost: 0.216555
Epoch  700/2000 Cost: 0.214939
Epoch  800/2000 Cost: 0.213403
Epoch  900/2000 Cost: 0.211942
Epoch 1000/2000 Cost: 0.210548
Epoch 1100/2000 Cost: 0.209220
Epoch 1200/2000 Cost: 0.207956
Epoch 1300/2000 Cost: 0.206755
Epoch 1400/2000 Cost: 0.205603
Epoch 1500/2000 Cost: 0.204509
Epoch 1600/2000 Cost: 0.203470
Epoch 1700/2000 Cost: 0.202474
Epoch 1800/2000 Cost: 0.201530
Epoch 1900/2000 Cost: 0.200628
Epoch 2000/2000 Cost: 0.199762
